name: Mainnet deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    concurrency: mainnet-deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

      - name: Get the current version ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=6144
          CI: false

          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_DONATION_ADDRESS: ${{ secrets.DONATION_ADDRESS }}
          VITE_ROOM_URL: ${{ secrets.ROOM_URL }}
          VITE_NETWORK: mainnet
          VITE_ACCOUNT_MINTER_CONTRACT: "0xf29C9415Bff38d3C22ebB87342252c309eDaC99B"
          VITE_POKO_ACCOUNT_MINTER_CONTRACT: "0x7e5CAA1cb07A8cb72bd8d670453a5dc070CF1384"
          VITE_FARM_CONTRACT: "0x2B4A66557A79263275826AD31a4cDDc2789334bD"
          VITE_GAME_CONTRACT: "0xfB84a7D985f9336987C89e1518E9A897b013080B"
          VITE_SESSION_CONTRACT: "0x63ED5e7dF3eF84B81dEc5aC46d46A8FD86c452b4"
          VITE_AUCTION_CONTRACT: "0x2E9F8FFD0A9C0D72D843fe4c6b531561AD365BAb"
          VITE_INVENTORY_CONTRACT: "0x22d5f9B75c524Fec1D6619787e582644CD4D7422"
          VITE_TOKEN_CONTRACT: "0xD1f9c58e33933a993A3891F8acFe05a68E1afC05"
          VITE_WISHING_WELL_CONTRACT: "0x24d32a94fA91d4C99f994622AF30Eb16bf76AEAC"
          VITE_PAIR_CONTRACT: "0x6f9e92dd4734c168a734b873dc3db77e39552eb6"
          VITE_DISCORD_REDIRECT: "https://sunflower-land.com/play/"
          VITE_CLIENT_VERSION: ${{ steps.date.outputs.date }}
          VITE_RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_RECAPTCHA_SITEKEY: "6Lfqm6MeAAAAAFS5a0vwAfTGUwnlNoHziyIlOl1s"
          VITE_CLOUDFLARE_CAPTCHA_SITEKEY: "0x4AAAAAAAAoLnsFOUvGeYp7"
          VITE_TRADER_CONTRACT: "0x1056A4ea959e3d84D6DC56Ac06B8Ff5B84648400"
          VITE_TREASURY_ADDRESS: "0x1DB57407EE80709D4d862fe81399FBB35B8B9586"
          VITE_FROG_CONTRACT: "0x52A5ddFF59E0A27a1cBA75c8045A434b7D296A6c"
          VITE_FROG_DONATION: "0xE3ac99Dc50fE9F0Ce9eCb5502399aee55F219448"
          VITE_TADPOLE_CONTRACT: "0xBFbF690E9D4929c95Ff63a38262fe6381d974D78"
          VITE_INCUBATOR_CONTRACT: "0x6aaD085B68CA1Cf01ac2AB0D2Bc814DE3b455EC1"
          VITE_WHITELIST_TOKEN_CONTRACT: "0x3f8a923DDa0C58ef6c353EFB8141007617Ab871c"
          VITE_QUEST_CONTRACT: "0xD0dBc2DAEBaf2E7b00895B23AD88532847a81aBB"
          VITE_SEAL_CONTRACT: "0x054c6bA53A64eC02Fc85857746111954d4822882"
          VITE_BUY_SFL_CONTRACT: "0x9E5Cd8b8D5B2329f1299a5c40B87feD55dA502D0"
          VITE_BUY_BLOCK_BUCKS_CONTRACT: "0x93a9DD356EC5208f8933Cb3607c4F61763798F29"
          VITE_QUICKSWAP_ROUTER_CONTRACT: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
          VITE_WMATIC_CONTRACT: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"
          VITE_DEPOSIT_CONTRACT: "0x9792d2BA541127D73B6c5b5eb25df7138dB4dB89"
          VITE_BUD_DEPOSIT_CONTRACT: "0xe01Fc29828Bd5E517F9B19dD37ef57D10150CC6a"
          VITE_GREEDY_GOBLIN_DONATION: "0xa85c0e9495ba7860c231b529258132b5c9075b8a"
          VITE_CHICKEN_FIGHT_DONATION: "0x74c0c166c919bbe0b160fc27fc58eeee361bdfd4"
          VITE_DAILY_REWARD_CONTRACT: "0x3F2f4AA023c6Ed149D342229afAc6E140E149114"
          VITE_WITHDRAWAL_CONTRACT: "0x83133174546453D99Ba7cf5e459bBA6Fb3A06b5d"
          VITE_CHRISTMAS_EVENT_DONATION: "0xE336EF65aC5532C0BfeFF52e350B22F96E784b6F"
          VITE_BUD_CONTRACT: "0x78a0cea8f323ff80985c5f9d1f9de18bb9e35996"

          VITE_ALCHEMY_RPC: ${{ secrets.ALCHEMY_RPC }}
          VITE_POKO_API_KEY: ${{ secrets.POKO_API_KEY }}
          VITE_POKO_DIRECT_CHECKOUT_API_KEY: ${{ secrets.POKO_DIRECT_CHECKOUT_API_KEY }}
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
          VITE_PRIVATE_IMAGE_URL: "https://sunflower-land.com/game-assets"

          VITE_BUMPKIN_DETAILS_CONTRACT: "0x687BcED586A8AECEdA5bd6b142577DE1d83a2a9c"
          VITE_BUMPKIN_ITEMS_CONTRACT: "0x4bb5b2461e9Ef782152c3a96698b2a4cF55B6162"
          VITE_BUMPKIN_CONTRACT: "0x624E4fa6980Afcf8EA27BFe08e2fB5979b64DF1C"
          VITE_GAME_ANALYTICS_APP_ID: ${{ secrets.GAME_ANALYTICS_APP_ID }}
          VITE_GAME_ANALYTICS_PUB_KEY: ${{ secrets.GAME_ANALYTICS_PUB_KEY }}
          VITE_DEQUIPPER_CONTRACT: "0x7BACA66955d219e645fAecbA2810f8Ecd4d674a9"
          VITE_SEQUENCE_ACCESS_KEY: ${{ secrets.SEQUENCE_ACCESS_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://sunflower-land.com/play --delete

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://www.sunflower-land.com/play --delete

      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
          content: "||@Certified Code Contributor ||"
          footer_title: "Changelog"
          footer_icon_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
          footer_timestamp: true

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}
          PATHS: "/play/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
